logging:
  level: debug
  path: ./

#redisson:
#  config:
#    type: single
#    address: redis://127.0.0.1:6379
#
#mybatis:
#    type-aliases-package: com.mars.yoyo.hotspot.order.domain
#    mapper-locations: classpath:mapper/*.xml
#
#mapper:
#    mappers:
#        - com.mars.yoyo.hotspot.mybatis.MyMapper
#    not-empty: false
#    identity: MYSQL
#
#pagehelper:
#    helperDialect: mysql
#    reasonable: true
#    supportMethodsArguments: true
#    params: count=countSql

server:
  port: 10009

#spring:
#  datasource:
#    master:
#      url: jdbc:mysql://localhost:3306/mifi?characterEncoding=UTF-8&autoReconnect=true&zeroDateTimeBehavior=convertToNull&useUnicode=true
#      username: root
#      password: 123456
#      # 初始化大小，最小，最大
#      initial-size: 5
#      min-idle: 5
#      max-active: 20
#      # 配置获取连接等待超时的时间
#      max-wait: 60000
#      # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
#      time-between-eviction-runs-millis: 60000
#      # 配置一个连接在池中最小生存的时间，单位是毫秒
#      min-evictable-idle-time-millis: 300000
#      #检测连接是否有效的sql
#      validation-query: SELECT 'x'
#      validation-query-timeout: 60000
#      test-while-idle: true
#      test-on-borrow: false
#      test-on-return: false
#    slave:
#      url: jdbc:mysql://localhost:3306/mifi?characterEncoding=UTF-8&autoReconnect=true&zeroDateTimeBehavior=convertToNull&useUnicode=true
#      username: root
#      password: 123456
#      # 初始化大小，最小，最大
#      initial-size: 5
#      min-idle: 5
#      max-active: 20
#      # 配置获取连接等待超时的时间
#      max-wait: 60000
#      # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
#      time-between-eviction-runs-millis: 60000
#      # 配置一个连接在池中最小生存的时间，单位是毫秒
#      min-evictable-idle-time-millis: 300000
#      #检测连接是否有效的sql
#      validation-query: SELECT 'x'
#      validation-query-timeout: 60000
#      test-while-idle: true
#      test-on-borrow: false
#      test-on-return: false
#    type: com.alibaba.druid.pool.DruidDataSource

paypal:
  client:
    id: AeI74paTgnvKNKLQdNviaCwzwEDjAlAs1jcrXL1H4hnvOCsLUDPFypof1A3QJg0bM5fuxOwotKQGvHYK
    secret: EBr9QsLsA2iTiUS1kt-8h1-b7SKzpgW9uyZB070o-8qqmYUNn4YcCYgXjB2RXmcg1ni0n1p5Rary5z6p
    mode: sandbox
