server:
  port: 11000
eureka:
  server:
    enable-self-preservation: false
    eviction-interval-timer-in-ms: 5000
    use-read-only-response-cache: false
  client:
      register-with-eureka: false
      fetch-registry: false
      service-url:
        defaultZone: http://localhost:11000/eureka
  instance:
    #prefer-ip-address: true
    instance-id: ${spring.application.name}:${spring.cloud.client.ipAddress}:${spring.application.instance_id:${server.port}}
    lease-renewal-interval-in-seconds: 5    # 续约更新时间间隔
    lease-expiration-duration-in-seconds: 10 # 续约到期时间



